services:
  frontend:
    build: frontend
    command: 'npm run dev'
    ports:
      - 5173:5173
    container_name: frontend
    restart: on-failure
    volumes:
      - ./frontend/src:/frontend/src
