version: '3.8'
services:
  backend:
    build:
      context: .
    ports:
      - "8090:8080"
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5555:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql


volumes:
  db:
    driver: local